// Product catalog with real brand data and Amazon/official image URLs
export const CATEGORIES = [
  {
    id: 1,
    name: 'Wireless',
    slug: 'wireless',
    description: 'Premium wireless headphones for untethered listening',
    icon: '📡',
    color: '#00d4ff',
    image: '/images/B08PZHYWJS.png',
  },
  {
    id: 2,
    name: 'Noise Cancelling',
    slug: 'noise-cancelling',
    description: 'Block out the world, dive into your music',
    icon: '🔇',
    color: '#7c3aed',
    image: '/images/B098FH5P3C.png',
  },
  {
    id: 3,
    name: 'Gaming',
    slug: 'gaming',
    description: 'Immersive audio for competitive gaming',
    icon: '🎮',
    color: '#10b981',
    image: '/images/B0B8T985R9.png',
  },
  {
    id: 4,
    name: 'Studio & Pro',
    slug: 'studio',
    description: 'Reference-grade headphones for professionals',
    icon: '🎛️',
    color: '#f59e0b',
    image: '/images/B00HVLUR86.png',
  },
  {
    id: 5,
    name: 'True Wireless Earbuds',
    slug: 'earbuds',
    description: 'Completely wireless freedom in your ears',
    icon: '🎵',
    color: '#ec4899',
    image: '/images/B0C3HVHMDM.png',
  },
  {
    id: 6,
    name: 'Budget Picks',
    slug: 'budget',
    description: 'Great sound without breaking the bank',
    icon: '💰',
    color: '#14b8a6',
    image: '/images/B095X7T381.png',
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: 'WH-1000XM5',
    brand: 'Sony',
    tagline: 'Industry-leading noise canceling headphones',
    description: 'The Sony WH-1000XM5 features HD Noise Canceling Processor QN2 and Auto NC Optimizer, providing outstanding noise-canceling performance. With 30+ hours of battery life and multipoint connection, it redefines premium wireless audio.',
    price: 29990,
    originalPrice: 34990,
    category: 'noise-cancelling',
    categoryId: 2,
    image: '/images/B09XS7JWHH.png',
    images: [
      '/images/B09XS7JWHH.png',
      '/images/B098FH5P3C.png',
      '/images/B09XS7JWHH.png',
    ],
    specs: {
      'Driver Size': '30mm',
      'Frequency Response': '4 Hz – 40,000 Hz',
      'Noise Canceling': 'Yes (8 microphones)',
      'Battery Life': '30 hours (NC on)',
      'Charging': 'USB-C, 3 min = 3 hours',
      'Connectivity': 'Bluetooth 5.2, NFC',
      'Weight': '250g',
      'Microphones': '8 mics',
    },
    rating: 4.8,
    reviewCount: 12847,
    stock: 50,
    isFeatured: true,
    badge: 'Best Seller',
  },
  {
    id: 2,
    name: 'QuietComfort 45',
    brand: 'Bose',
    tagline: 'Noise cancelling headphones, certified for humans',
    description: 'The Bose QuietComfort 45 headphones deliver legendary Bose quiet. TriPort Acoustic architecture and Volume Optimized EQ deliver full, lifelike audio at every volume level. Two modes — Quiet Mode and Aware Mode — keep you in control.',
    price: 32000,
    originalPrice: 37990,
    category: 'noise-cancelling',
    categoryId: 2,
    image: '/images/B098FH5P3C.png',
    images: [
      '/images/B098FH5P3C.png',
      '/images/B098FH5P3C.png',
    ],
    specs: {
      'Driver Size': 'Custom 40mm',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Noise Canceling': 'Yes (Bose Active EQ)',
      'Battery Life': '22 hours',
      'Charging': 'USB-C',
      'Connectivity': 'Bluetooth 5.1',
      'Weight': '240g',
      'Microphones': '4 mics',
    },
    rating: 4.7,
    reviewCount: 8923,
    stock: 35,
    isFeatured: true,
    badge: 'Top Rated',
  },
  {
    id: 3,
    name: 'AirPods Max',
    brand: 'Apple',
    tagline: 'A feel-good audio experience',
    description: 'AirPods Max combine high-fidelity audio with industry-leading Active Noise Cancellation to deliver an unparalleled listening experience. Each part of AirPods Max has been designed to create an exceptional acoustic system.',
    price: 59900,
    originalPrice: 64900,
    category: 'wireless',
    categoryId: 1,
    image: '/images/B08PZHYWJS.png',
    images: [
      '/images/B08PZHYWJS.png',
      '/images/B08PZHYWJS.png',
    ],
    specs: {
      'Driver Size': '40mm Apple-developed dynamic driver',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Noise Canceling': 'Yes (Active Noise Cancellation)',
      'Battery Life': '20 hours',
      'Charging': 'USB-C',
      'Connectivity': 'Bluetooth 5.0, H1 chip',
      'Weight': '385g',
      'Microphones': '9 mics',
    },
    rating: 4.6,
    reviewCount: 6210,
    stock: 20,
    isFeatured: true,
    badge: 'Premium',
  },
  {
    id: 4,
    name: 'Studio Pro',
    brand: 'Beats',
    tagline: 'Lossless audio. Zero compromise.',
    description: 'Studio Pro delivers personalized spatial audio with dynamic head tracking, lossless audio quality with USB-C, and up to 40 hours of battery life. The professional-grade headphones reimagined for everyday life.',
    price: 27900,
    originalPrice: 31990,
    category: 'wireless',
    categoryId: 1,
    image: '/images/B0C8PRPMXP.png',
    images: [
      '/images/B0C8PRPMXP.png',
    ],
    specs: {
      'Driver Size': 'Custom 40mm',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Noise Canceling': 'Yes (ANC + Transparency)',
      'Battery Life': '40 hours (ANC off)',
      'Charging': 'USB-C, 3.5mm',
      'Connectivity': 'Bluetooth 5.3, Apple W1 chip',
      'Weight': '260g',
      'Microphones': '4 mics',
    },
    rating: 4.5,
    reviewCount: 3847,
    stock: 28,
    isFeatured: false,
    badge: null,
  },
  {
    id: 5,
    name: 'Quantum 910',
    brand: 'JBL',
    tagline: 'Head-tracking spatial sound — no console required',
    description: 'JBL Quantum 910 features Head-Tracking Spatial Sound that shifts as you move your head, JBL QuantumSPHERE 360 technology, and Active Noise Cancelling. Compatible with PC, console, and mobile.',
    price: 14999,
    originalPrice: 19999,
    category: 'gaming',
    categoryId: 3,
    image: '/images/B0B8T985R9.png',
    images: [
      '/images/B0B8T985R9.png',
    ],
    specs: {
      'Driver Size': '40mm',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Microphone': 'Detachable boom + beamforming',
      'Battery Life': '34 hours',
      'Charging': 'USB-C',
      'Connectivity': 'Bluetooth 5.0, 3.5mm, USB',
      'Weight': '340g',
      'Platform': 'PC, PS, Xbox, Switch, Mobile',
    },
    rating: 4.4,
    reviewCount: 2156,
    stock: 42,
    isFeatured: true,
    badge: 'Gaming Pro',
  },
  {
    id: 6,
    name: 'Arctis Nova Pro',
    brand: 'SteelSeries',
    tagline: 'The premium gaming audio benchmark',
    description: 'The Arctis Nova Pro Wireless is a premium gaming headset with superior acoustic performance, 360° spatial audio with 2 hot-swap batteries for infinite playtime, and ClearCast AI noise-cancelling mic.',
    price: 22999,
    originalPrice: 27999,
    category: 'gaming',
    categoryId: 3,
    image: '/images/B09ZWKD9TF.png',
    images: [
      '/images/B09ZWKD9TF.png',
    ],
    specs: {
      'Driver Size': '40mm Hi-Fi',
      'Frequency Response': '10 Hz – 40,000 Hz',
      'Microphone': 'Retractable ClearCast AI',
      'Battery Life': 'Infinite (hot-swap dual battery)',
      'Charging': 'USB-C base',
      'Connectivity': 'Bluetooth 5.0 + 2.4GHz lossless',
      'Weight': '338g',
      'Platform': 'PC, PS5, PS4',
    },
    rating: 4.7,
    reviewCount: 4532,
    stock: 18,
    isFeatured: false,
    badge: null,
  },
  {
    id: 7,
    name: 'ATH-M50x',
    brand: 'Audio-Technica',
    tagline: 'Critically acclaimed studio performance',
    description: 'The ATH-M50x professional monitor headphones are engineered for studio use and feature outstanding clarity throughout an extended frequency range, with deep, accurate bass response. Legendary for mixing and mastering.',
    price: 12990,
    originalPrice: 15990,
    category: 'studio',
    categoryId: 4,
    image: '/images/B00HVLUR86.png',
    images: [
      '/images/B00HVLUR86.png',
    ],
    specs: {
      'Driver Size': '45mm large-aperture',
      'Frequency Response': '15 Hz – 28,000 Hz',
      'Impedance': '38 ohms',
      'Sensitivity': '99 dB',
      'Connectivity': '3.5mm + 6.3mm adapter',
      'Weight': '285g',
      'Cable': 'Detachable 3 cables included',
      'Type': 'Closed-back, circumaural',
    },
    rating: 4.8,
    reviewCount: 15600,
    stock: 60,
    isFeatured: true,
    badge: 'Studio Classic',
  },
  {
    id: 8,
    name: 'HD 660S2',
    brand: 'Sennheiser',
    tagline: 'Open-back audiophile excellence',
    description: 'The Sennheiser HD 660S2 is an audiophile-grade open-back dynamic headphone with improved bass extension and a highly refined acoustic design. Featuring a new 300-ohm transducer for superior resolution.',
    price: 45000,
    originalPrice: 49990,
    category: 'studio',
    categoryId: 4,
    image: '/images/B0BRP1F6B1.png',
    images: [
      '/images/B0BRP1F6B1.png',
    ],
    specs: {
      'Driver Size': '38mm lightweight aluminium voice coil',
      'Frequency Response': '8 Hz – 41,500 Hz',
      'Impedance': '300 ohms',
      'Sensitivity': '104 dB',
      'Connectivity': '6.35mm, 4.4mm balanced, XLR',
      'Weight': '260g',
      'Type': 'Open-back, circumaural',
      'THD': '< 0.04% (1 kHz, 100 dB)',
    },
    rating: 4.9,
    reviewCount: 1823,
    stock: 12,
    isFeatured: false,
    badge: 'Audiophile',
  },
  {
    id: 9,
    name: 'WF-1000XM5',
    brand: 'Sony',
    tagline: 'The best truly wireless earbuds',
    description: 'Sony WF-1000XM5 earbuds deliver industry-leading noise canceling in the smallest, lightest design yet. Featuring the HD Noise Canceling Processor QN2e and two Bluetooth chips for superior connectivity.',
    price: 19990,
    originalPrice: 24990,
    category: 'earbuds',
    categoryId: 5,
    image: '/images/B0C3HVHMDM.png',
    images: [
      '/images/B0C3HVHMDM.png',
    ],
    specs: {
      'Driver Size': '8.4mm',
      'Frequency Response': '20 Hz – 40,000 Hz',
      'Noise Canceling': 'Yes (Integrated Processor V2)',
      'Battery Life': '8 hours (36 hours with case)',
      'Charging': 'USB-C, Qi wireless',
      'Connectivity': 'Bluetooth 5.3, Multipoint',
      'Weight': '5.9g each',
      'Water Resistance': 'IPX4',
    },
    rating: 4.7,
    reviewCount: 7234,
    stock: 45,
    isFeatured: true,
    badge: 'Best Earbuds',
  },
  {
    id: 10,
    name: 'Galaxy Buds2 Pro',
    brand: 'Samsung',
    tagline: 'Intelligent ANC. Hi-Fi sound.',
    description: 'Galaxy Buds2 Pro packs outstanding audio hardware into a compact ergonomic design. Featuring Intelligent Active Noise Cancellation, 360° Audio with head tracking, and 24-bit Hi-Fi audio.',
    price: 14999,
    originalPrice: 17999,
    category: 'earbuds',
    categoryId: 5,
    image: '/images/B0B39RXXSF.png',
    images: [
      '/images/B0B39RXXSF.png',
    ],
    specs: {
      'Driver Size': '10mm woofer + 6.1mm tweeter',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Noise Canceling': 'Yes (Intelligent ANC)',
      'Battery Life': '5 hours (18 hours with case)',
      'Charging': 'USB-C, Qi wireless',
      'Connectivity': 'Bluetooth 5.3',
      'Weight': '5.5g each',
      'Water Resistance': 'IPX7',
    },
    rating: 4.5,
    reviewCount: 5678,
    stock: 38,
    isFeatured: false,
    badge: null,
  },
  {
    id: 11,
    name: 'Tune 760NC',
    brand: 'JBL',
    tagline: 'Active Noise Cancelling on a budget',
    description: 'JBL Tune 760NC delivers the legendary JBL Pure Bass Sound with Active Noise Cancelling, multi-point connection, and up to 35 hours of battery life. Lightweight, foldable, and available in vibrant colors.',
    price: 4999,
    originalPrice: 7999,
    category: 'budget',
    categoryId: 6,
    image: '/images/B095X7T381.png',
    images: [
      '/images/B095X7T381.png',
    ],
    specs: {
      'Driver Size': '40mm',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Noise Canceling': 'Yes (Active)',
      'Battery Life': '35 hours (ANC on)',
      'Charging': 'USB-C',
      'Connectivity': 'Bluetooth 5.0, multi-point',
      'Weight': '249g',
      'Type': 'Closed-back',
    },
    rating: 4.3,
    reviewCount: 9123,
    stock: 80,
    isFeatured: false,
    badge: 'Best Value',
  },
  {
    id: 12,
    name: 'Evolve2 85',
    brand: 'Jabra',
    tagline: 'Professional wireless headset redefined',
    description: "Jabra Evolve2 85 is the world's best professional headset. With unprecedented 8-mic technology, Advanced Active Noise Cancellation, and a premium leather memory foam cushion for all-day comfort.",
    price: 42000,
    originalPrice: 47990,
    category: 'noise-cancelling',
    categoryId: 2,
    image: '/images/B08761X7L2.png',
    images: [
      '/images/B08761X7L2.png',
    ],
    specs: {
      'Driver Size': 'Custom 40mm',
      'Frequency Response': '20 Hz – 20,000 Hz',
      'Noise Canceling': 'Yes (Advanced ANC)',
      'Battery Life': '37 hours',
      'Charging': 'USB-C, Qi wireless',
      'Connectivity': 'Bluetooth 5.0, USB-A/C dongle',
      'Weight': '340g',
      'Microphones': '8 professional mics',
    },
    rating: 4.6,
    reviewCount: 1245,
    stock: 15,
    isFeatured: false,
    badge: 'Pro Choice',
  },
];

export const COUPONS = [
  { code: 'HACKOVER10', type: 'percent', value: 10, minOrder: 1000 },
  { code: 'SOUND500', type: 'flat', value: 500, minOrder: 5000 },
  { code: 'NEWUSER20', type: 'percent', value: 20, minOrder: 2000 },
];

export function formatPrice(price) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(price);
}

export function getProductsByCategory(slug) {
  return PRODUCTS.filter(p => p.category === slug);
}

export function getFeaturedProducts() {
  return PRODUCTS.filter(p => p.isFeatured);
}

export function searchProducts(query) {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  );
}
